import assert from "node:assert/strict";
import { readFileSync } from "node:fs";

await import("../src/defaults.js");

const ghzh = globalThis.GHZH_DEFAULTS;
const manifest = JSON.parse(readFileSync(new URL("../manifest.json", import.meta.url), "utf8"));

assert.equal(ghzh.translateUiText("Pull requests"), "拉取请求");
assert.equal(ghzh.translateUiText("12 stars"), "12 星标");
assert.equal(ghzh.translateUiText("Updated 2 days ago"), "2 天前更新");
assert.equal(ghzh.translateUiText("Security and quality"), "安全与质量");
assert.equal(ghzh.translateUiText("Folders and files"), "文件夹和文件");
assert.equal(ghzh.translateUiText("last month"), "上个月");
assert.equal(ghzh.translateUiText("stars"), "星标");
assert.equal(ghzh.translateUiText("watching"), "关注者");
assert.equal(ghzh.translateUiText("forks"), "派生");
assert.equal(ghzh.translateUiText("Platform"), "平台");
assert.equal(ghzh.translateUiText("Solutions"), "解决方案");
assert.equal(ghzh.translateUiText("Open Source"), "开源");
assert.equal(ghzh.translateUiText("Pricing"), "定价");
assert.equal(ghzh.translateUiText("Home"), "首页");
assert.equal(ghzh.translateUiText("All issues"), "全部议题");
assert.equal(ghzh.translateUiText("All pull requests"), "全部拉取请求");
assert.equal(ghzh.translateUiText("All repositories"), "全部仓库");
assert.equal(ghzh.translateUiText("Top repositories"), "常用仓库");
assert.equal(ghzh.translateUiText("MCP registry"), "MCP 注册表");
assert.equal(ghzh.translateUiText("Feed"), "动态");
assert.equal(ghzh.translateUiText("Read more"), "阅读更多");
assert.equal(ghzh.translateUiText("Write code"), "编写代码");
assert.equal(ghzh.translateUiText("Trending"), "趋势");
assert.equal(ghzh.translateUiText("Developers"), "开发者");
assert.equal(ghzh.translateUiText("Spoken Language: Any"), "自然语言：任意");
assert.equal(ghzh.translateUiText("Language: Any"), "编程语言：任意");
assert.equal(ghzh.translateUiText("Date range: Today"), "日期范围：今天");
assert.equal(ghzh.translateUiText("1,531 stars today"), "今天 1,531 个星标");
assert.equal(ghzh.translateUiText("star 120,040"), "120,040 星标");
assert.equal(ghzh.translateUiText("fork 6,417"), "6,417 派生");
assert.equal(ghzh.translateUiText("Sponsor @freeCodeCamp"), "赞助 @freeCodeCamp");
assert.equal(ghzh.translateUiText("Folders"), "文件夹");
assert.equal(ghzh.translateUiText("Done"), "完成");
assert.equal(ghzh.translateUiText("Assigned"), "分配给我");
assert.equal(ghzh.translateUiText("Review requested"), "请求我审查");
assert.equal(ghzh.translateUiText("Sort by: Newest to oldest"), "排序：从新到旧");
assert.equal(ghzh.translateUiText("Search stars"), "搜索星标");
assert.equal(ghzh.translateUiText("Type: All"), "类型：全部");
assert.equal(ghzh.translateUiText("Language"), "语言");
assert.equal(ghzh.translateUiText("Sort by: Recently starred"), "排序：最近星标");
assert.equal(ghzh.translateUiText("Starred"), "已星标");
assert.equal(ghzh.translateUiText("3 repositories"), "3 个仓库");
assert.equal(ghzh.translateUiText("2 followers"), "2 关注者");
assert.equal(ghzh.translateUiText("0 following"), "0 正在关注");
assert.equal(ghzh.translateUiText("Showing 0-18 of 158 items"), "显示第 0-18 项，共 158 项");
assert.equal(ghzh.translateUiText("Clear out the clutter."), "清理杂乱通知。");
assert.equal(ghzh.hasAiConfig(ghzh.mergeSettings({ ai: { baseUrl: "http://localhost:11434/v1", model: "qwen2.5" } })), true);
assert.equal(ghzh.hasAiConfig(ghzh.mergeSettings({ ai: { baseUrl: "https://api.openai.com/v1", model: "gpt-4.1-mini" } })), false);
assert.equal(ghzh.looksLikeProtectedName("openai/openai-cookbook"), true);
assert.equal(ghzh.looksLikeProtectedName("LangChain"), true);
assert.equal(ghzh.looksLikeProtectedName("repository"), false);
assert.ok(ghzh.extractProtectedTerms("LangChain agents in openai/openai-cookbook use Qwen2.5.").includes("LangChain"));
assert.ok(manifest.commands["toggle-extension"]);
assert.ok(manifest.commands["translate-page"]);

console.log("smoke tests passed");
